version: '3.8'

networks:
  polkadot-wizard:
    name: polkadot-wizard 

services:
  web:
    container_name: ${CONTAINER_BASE}_web
    build:
      context: .
      dockerfile: .docker/web/dev.Dockerfile
      target: runner
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - ${WEB_EXTERNAL_PORT}:3000
    environment:
      - NODE_ENV=${WEB_ENVIRONMENT}
      - .env
      - NEXT_PUBLIC_BACKEND_API=http://compiler-be:8000
    networks:
      - polkadot-wizard
    depends_on:
      - compiler-be
    command: yarn dev
  compiler-be:
    container_name: ${CONTAINER_BASE}_backend
    build:
      context: ./ink-compiler-be
      dockerfile: ./Dockerfile
    ports:
      - ${BACKEND_EXTERNAL_PORT}:8000
    environment:
      - MONGOURI=mongodb://mongodb:27017
    networks:
      - polkadot-wizard
    depends_on:
      - mongodb
  mongodb:
    ports:
      - ${DB_EXTERNAL_PORT}:27017
    container_name: ${CONTAINER_BASE}_mongodb
    restart: always
    logging:
        options:
            max-size: 1g
    image: mongo:5.0.16
    networks:
      - polkadot-wizard
  

  