version: '3.8'

services:
  web:
    container_name: ${CONTAINER_BASE}_web
    build:
      context: ../
      dockerfile: .docker/node.Dockerfile
    ports:
      - ${WEB_EXTERNAL_PORT}:3000
    environment:
      - NODE_ENV=${WEB_ENVIRONMENT}
